### ISSUE TITLE
Supported locales?

### ISSUE THREAD

**Issue by Elijen** [react-native-datetimepicker/datetimepicker#300]
What are the supported locales/languages for the DateTimePicker on iOS and Android?

When I set the iPhone language to Swedish and omit the `locale` prop the DateTimePicker is still displayed in English.

**Comment by ksielyov** [comment]
Same problem. Can`t change to RU

**Comment by alesdvorakcz** [comment]
I have similar problem.
When I set locale only month is translated, week days and "Time" is still in english.
v3.0.9

<img width="246" alt="image" src="https://user-images.githubusercontent.com/1890782/105840086-688f5f80-600d-11eb-9b3a-7159d343f63d.png">

**Comment by mindaugasnakrosis** [comment]
Up

**Comment by SuperBigBang** [comment]
Up! Wrong locale day of week:
![image](https://user-images.githubusercontent.com/42957934/108584620-34962880-7386-11eb-85fb-e2cb7b756941.png)

**Comment by YaoHuiJi** [comment]
I think this is a bug of UIDatePicker in iOS 14. because I wrote a native app for testing and also found this problem. why it still exists in iOS 14.4? 🤷‍♂️
![Simulator Screen Shot - iPhone 11 - 2021-03-31 at 20 02 58](https://user-images.githubusercontent.com/741543/113141509-5d9aba80-925c-11eb-91f9-d98e627975e9.png)

**Comment by auguyon** [comment]
Same issue here ! Any solutions ?

**Comment by vonovak** [comment]
closed by https://github.com/react-native-datetimepicker/datetimepicker/pull/540 (v5 release)
