### ISSUE TITLE
Expo Web support

### ISSUE THREAD

**Issue by ltaljaard** [react-native-datetimepicker/datetimepicker#318]
There are no decent Date / Time pickers available for Expo Web. Is it on the roadmap to add support for Expo Web?

**Comment by nandorojo** [comment]
I was thinking the same. More discussion at https://github.com/mmazzarolo/react-native-modal-datetime-picker

**Comment by ltaljaard** [comment]
I have posted some code that could be used to add support for Expo Web/React Native Web - or a separate npm module could be created if you don't want to integrate it into react-native-datetimepicker: [https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/481](url)

**Comment by vonovak** [comment]
Hello!
adding web support is not on the roadmap.

I personally don't have such plans because it means one more thing to maintain :smile: and because of #313.

If someone steps in and says "We need web support because of X and Y and I'll implement it and keep maintaining the code, docs and tests" then _maybe_ yes. But at the moment I'm not convinced we should have web support..? I bet there are dozens of react date pickers for the web, with gazillion of configuration options that may not be available on all platforms and people will (understandably!) complain that some option is only available on web, and not on ios and android...
I think if people choose whichever datepicker they want for web, and then use it, is better than us forcing some datepicker on them. BUT at the same time I haven't done any research on this and I haven't had a thorough discussion. 

I understand people want web support, but before we do anything, I'd like to see someone think about it more deeply than that and lay out arguments for why we should support web, what are the alternatives, and how it should be done.

Thank you, hope you understand!

**Comment by ltaljaard** [comment]
Sure, that's understandable 😀

**Comment by vonovak** [comment]
given there has been one year without activity, I'm closing this
