### ISSUE TITLE
Remove peer dependency for react-native-windows when not building for windows

### ISSUE THREAD

**Issue by dbarner1** [react-native-datetimepicker/datetimepicker#341]
# Feature request
Hi, It looks like this package requires react-native-windows when building for a react-native app.  Could this be not required?  Or, is it required for a valid reason?

## Why it is needed

Smaller package with only the required bits needed.

## Possible implementation
I can try to help here. :/

### Code sample

n/a

**Comment by rectified95** [comment]
This PR moved RNW back from an optionalDep to peerDep and explains in detail why the warning you're seeing is ignorable. tl;dr peer dependencies don't get automatically installed, and since your app doesn't rely on RNW features nothing bad will happen.
https://github.com/react-native-datetimepicker/datetimepicker/pull/267
