### ISSUE TITLE
ViewPropTypes is deprecated

### ISSUE THREAD

**Issue by billnbell** [react-native-datetimepicker/datetimepicker#595]
ViewPropTypes is deprecated

use deprecated lib.

**Comment by glaucopgomes** [comment]
ViewPropTypes support is removed on react-native 0.69.0

**Comment by brantsrasmus** [comment]
Will this be addressed? If used in Expo SDK 46 this will break the app because of react-native 0.69.4

**Comment by t-leclercq** [comment]
Bump
Is a patch with `deprecated-react-native-prop-types` module possible ?
Do you guys need a PR ?

**Comment by vonovak** [comment]
Hello and thanks for reporting,
The ViewProps that this lib is using are from here https://github.com/facebook/react-native/blob/e0a71fc7b5cb8c264000147099be5b2575931193/Libraries/Components/View/ViewPropTypes.js#L402

and they still exists. Please add a minimum reproduction, otherwise this is not actionable, thank you.

Thank you 🙂

**Comment by RRaideRR** [comment]
> Will this be addressed? If used in Expo SDK 46 this will break the app because of react-native 0.69.4

I also thought the same. However, I just [built a small snack](https://snack.expo.dev/@raider/4e1d92) and it works.

**Comment by vonovak** [comment]
Hello, I don't belive we're using the deprecated package in this lib and so I'm going to close the issue.
