### ISSUE TITLE
Unable to open xcodeproj in Xcode

### ISSUE THREAD

**Issue by konjoinfinity** [react-native-datetimepicker/datetimepicker#719]
# Bug report
<img width="284" alt="Screen Shot 2023-02-06 at 1 36 20 PM" src="https://user-images.githubusercontent.com/46323883/217056707-91dcc244-469c-4b7a-b955-814cf83b6446.png">

## Summary

Unable to open the project in xcode, see screenshot.

## Reproducible sample code

No code, only when opening the .xcodeproj file.

## Steps to reproduce

Open RNDateTimePicker.xcodeproj in Xcode 14.2
Error message

Describe what you expected to happen:

Should be able to open the project in xcode to inspect the files, wishing to contribute to the project.

## Environment info

Macbook pro Monterey 12.6.1
Xcode 14.2

datetimepicker version: 6.7.3

iOS / Android version: N/A

**Comment by vonovak** [comment]
Hello and thanks for asking,
in order to contribute, you'll want to open the xcode workspace (not project) file of the example app that you'll find here: https://github.com/react-native-datetimepicker/datetimepicker/tree/master/example/ios

in that folder you first need to run `pod install` to generate the workspace file

Hope this helps
Thank you 🙂
